### ISSUE TITLE
Termux rvx builder issue

### ISSUE THREAD

**Issue by Adity1243** [YT-Advanced/YT-Advanced#10]
Can you explain how to download your patches.

**Comment by YoghurtAndPizza** [comment]
The easiest way to download the patches is with Revancify, read the document:

https://github.com/YT-Advanced/revanced-documentation

Download Termux from Github, use this command in Termux:

`pkg update -y && pkg install git -y && git clone https://github.com/decipher3114/Revancify.git && ./Revancify/revancify`

It will install Revancify, when it asks you to select Source, select ReX and it will download the things you need for you. Then just select the patches you want and patch.

**Comment by Adity1243** [comment]
Yes i tried on rvx builder and it using inotia00 sources patches i saw some patches are here uploaded but rvx builder are not downloading them,its downloading inotia00 patches

**Comment by YoghurtAndPizza** [comment]
Follow the instructions in the documentation, if you're having issues switching to different source then you could try to uninstall Termux (if you're on Android), and then reinstall it following the steps in the documentation.

**Comment by Adity1243** [comment]
/
![Screenshot_2023-08-11-01-05-17-501_com microsoft emmx](https://github.com/YT-Advanced/YT-Advanced/assets/131557644/349b8a52-7c0d-4b36-a3f5-5a5a807faf66)

CCan you tell me how to set your patch source here.

**Comment by YoghurtAndPizza** [comment]
You can try changing "Patches Organization" to YT-Advanced, "Patches Source" to ReX-patches, "Integrations Organization" to YT-Advanced and "Integrations Source" to ReX-integrations.

"Cli Organization" and "Cli Source" doesn't need to be changed.

**Comment by Adity1243** [comment]
It showing error while patching 

[builder] java.io.FileNotFoundException: /data/data/com.termux/files/home/rvx-builder/revanced (Is a directory) at java.base/java.io.RandomAccessFile.open0(Native Method) at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:344) at java.base/java.io.RandomAccessFile.(RandomAccessFile.java:259) at java.base/java.io.RandomAccessFile.(RandomAccessFile.java:213) at java.base/java.util.zip.ZipFile$Source.(ZipFile.java:1294) at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1259) at java.base/java.util.zip.ZipFile$CleanableResource.(ZipFile.java:708) at java.base/java.util.zip.ZipFile.(ZipFile.java:242) at java.base/java.util.zip.ZipFile.(ZipFile.java:172) at java.base/java.util.jar.JarFile.(JarFile.java:347) at java.base/java.util.jar.JarFile.(JarFile.java:318) at java.base/java.util.jar.JarFile.(JarFile.java:284) at app.revanced.patcher.util.patch.PatchBundle$Jar.loadPatches(PatchBundle.kt:51) at app.revanced.cli.command.MainCommand.run(MainCommand.kt:149) at picocli.CommandLine.executeUserObject(CommandLine.java:2026) at picocli.CommandLine.access$1500(CommandLine.java:148) at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) at picocli.CommandLine.execute(CommandLine.java:2170) at app.revanced.cli.main.MainKt.main(Main.kt:7)

**Comment by YoghurtAndPizza** [comment]
That might be caused by options.json file, you need to uninstall and reinstall, then try again.

**Comment by Adity1243** [comment]
The rvx termux link didnt got updated i guess bcus its using rvx builder v3.9.8 althought v3.9.9 is released but it showing it has latest version.

**Comment by Adity1243** [comment]
And using inotia00 sources as default.

**Comment by YoghurtAndPizza** [comment]
I wish I had more experience about RVX-Builder my friend, I tried my best. You need to wait YT-Advanced's help on this one.

In the nean time you could give Revancify a shot, I'm using it and successfully patched using YT-Advanced's source.

**Comment by Adity1243** [comment]
For me rvx termux is best i patched youtube from  starting with inotia00 patches and its easy for me. i tried revancify but it always given errors to me while installing in my termux, i will try rvx builder windows if it works.

**Comment by YT-Advanced** [comment]
Dear @Adity1243, You should read this docmentation (I have updated the RVX Builder to my own):
https://github.com/YT-Advanced/revanced-documentation/wiki/Method-2.-Using-RVX-Builder-(Windows-MacOS-Linux-Android)#using-rvx-builder-android---termux

**Comment by Adity1243** [comment]
Yes but its showing error while patching in rvx builder termux and widows both.

**Comment by Adity1243** [comment]
https://github.com/YT-Advanced/YT-Advanced/issues/10#issuecomment-1673874648

**Comment by Adity1243** [comment]
I tried can you test by yourself if you find same error as me.

**Comment by YT-Advanced** [comment]
Okay, I will test soon (Now I'm quite busy)

**Comment by Adity1243** [comment]
Nope same error coming as always and its not updating to v3.9.9 its using v3.9.8 and showing latest version using
https://github.com/YT-Advanced/YT-Advanced/issues/10#issuecomment-1673874648

**Comment by Adity1243** [comment]
In windows if i try it also used v3.9.8 even if i downloaded from your documentation.

**Comment by YT-Advanced** [comment]
> In windows if i try it also used v3.9.8 even if i downloaded from your documentation.

Yes, I know. This is because I didn't update the version, but it is v3.9.9

**Comment by Adity1243** [comment]
Ok i done with revancify.

**Comment by GucekPL** [comment]
same error as mentioned above, I'm using v3.9.9 (in program is v3.9.8), I tried deleting and downloading again, deleting files of settings and option and using inotia's builder. Nothing helped

**Comment by GucekPL** [comment]
v.4.0.0 - same issue

**Comment by YT-Advanced** [comment]
> v.4.0.0 - same issue

Hmm, sad. I have no idea to solve it :(

**Comment by GucekPL** [comment]
> Hmm, sad. I have no idea to solve it :(
I will try delete ALL the files of builder because deleting exe don't delete settings of builder (still I have my HEX color #e4103e). Do you know where the files of builder is located?

**Comment by GucekPL** [comment]
I tested YOUR builder by changing source's to inotia's repo and all worked. I think problem is in code of your patches or someting similar

**Comment by YT-Advanced** [comment]
> I tested YOUR builder by changing source's to inotia's repo and all worked. I think problem is in code of your patches or someting similar

Maybe it is because the `-` in my username ?

**Comment by GucekPL** [comment]
I was just wondering if it was an issue with your username. Strange that. Possibly that's the problem. Through the CLI I was able to patch normally

**Comment by cooperbeaman** [comment]
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/b7506939-1752-4144-b158-c08d6125ca63)
😥. Got excited after updating to version 4.0.0, but now this same error appears. Hopefully it's a simple fix.

**Comment by lowestprime** [comment]
> ![image](https://user-images.githubusercontent.com/55124795/260641451-b7506939-1752-4144-b158-c08d6125ca63.png) disappointed_relieved. Got excited after updating to version 4.0.0, but now this same error appears. Hopefully it's a simple fix.

🤔
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/981a64c1-8013-4678-b23e-27503140ee4e)

**Comment by YT-Advanced** [comment]
Can anyone test latest build ?

**Comment by GucekPL** [comment]
Hmm, that `_` in .json file shouldn't be, and by some miracle it is

**Comment by YT-Advanced** [comment]
> Hmm, that `_` in .json file shouldn't be, and by some miracle it is

It is the current text point (like in Word and notepad we have | )

**Comment by YT-Advanced** [comment]
@GucekPL I have fully fixed it in v4.0.2 ! Can you go and check :D

**Comment by lowestprime** [comment]
Now it won't even install or update. Already did full reinstall of termux clear data and cache .
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/a19737d7-2db8-4a26-9d2b-c418b6c4bd06)

**Comment by GucekPL** [comment]
Same problem. On Windows terminal is opening and instantly closing.

**Comment by YT-Advanced** [comment]
@GucekPL Sorry, I have forgot something. I have released again v4.0.0. Can u check it

**Comment by lowestprime** [comment]
Thank you for your responsiveness. Now, after clean install termux etc, still getting errors:
At launch:
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/6c0f89a6-2a0f-43bb-9c87-fa79ca8ba91e)

Gets to here without error:
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/19b0e977-0134-4633-aa9a-ae69b740ea4b)

Finally fails with this:
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/9ca2e7af-6ae0-4add-adda-93d09510c584)

**Comment by YT-Advanced** [comment]
Please do a clean install bro

**Comment by YT-Advanced** [comment]
Here is the command if you didn't know how to reinstall
```
./rvx-builder.sh reinstall && ./rvx-builder.sh run

**Comment by lowestprime** [comment]
I know, just did again, same result as clean termux reinstall.
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/8ed7dd8a-d4b2-489b-b7e7-671d23dc0c9d)

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/3ff60245-b31c-488b-b821-9d11f22ce287)

**Comment by lowestprime** [comment]
Now display same outdated version warning for 4.0.0-stable:
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/5088ac89-09b7-4475-b06a-63524c5e346f)

**Comment by lowestprime** [comment]
Good work King! 🙏
![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/81e9c400-7ee4-4e85-8309-e44a11779db9)

![image](https://github.com/YT-Advanced/YT-Advanced/assets/55124795/328afb0f-23ee-42f5-8519-c06194d85d05)

**Comment by Adity1243** [comment]
Why apkmirror api not accessible in rvx builder and revancify both

**Comment by Adity1243** [comment]
Ok it got fixed

**Comment by YT-Advanced** [comment]
> Ok it got fixed

Sometime apkmirror server turn on CloudFlare Captcha .-.
