### ISSUE TITLE
Bug: Hide Quality Layout Footer patch is not working

### ISSUE THREAD

**Issue by MrNorthernLights** [YT-Advanced/YT-Advanced#112]
YouTube: 18.34.37
Patches: 2.190.0
Patching Tool: Revanced Manager 1.9.4 & RVX Builder 5.1.0

![image](https://github.com/YT-Advanced/YT-Advanced/assets/143272767/af3fc1ff-d1f9-450e-9774-0a648189b2d9)

![image](https://github.com/YT-Advanced/YT-Advanced/assets/143272767/996c31c5-cf6a-4262-bfce-a7acc935b0e6)

I have uninstalled everything and reinstalled, still not working. And yes, I restarted YouTube after enabling the setting, still not working.

**Comment by YT-Advanced** [comment]
@kazimmt Hmm, Can u add litho compoment into indentifier group and test ?

**Comment by MrNorthernLights** [comment]
Im so tired of using revanced manager, its constantly adding in patches that I excluded. I uninstalled everything and will not install again until ReX is supporting revancify again.

I dont care if this bug gets fixed or not, so Im closing it.

Bring revancify support back please, its light years ahead of shitty revanced manager.

**Comment by MrNorthernLights** [comment]
I reinstalled everything, and patched with RVX Builder 5.1.0, the same issue continues.

**Comment by YT-Advanced** [comment]
> I reinstalled everything, and patched with RVX Builder 5.1.0, the same issue continues.

I know, you just need to stay and wait a fix from me

**Comment by YT-Advanced** [comment]
Fixed in lastest version

**Comment by StradivariusKane** [comment]
Still not working.

![Screenshot_20230909_161739_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/144253206/50a507ba-19f6-4986-b027-1d83e7f284ab)

YouTube 18.35.35, patches 2.190.1.

@YT-Advanced

**Comment by YT-Advanced** [comment]
Can confirm it

**Comment by Kantotero** [comment]
> Can confirm it

My issue got closed.. so I'll just follow-up here. The `hide captions menu footer` also not working

![IMG_20230909_220630_537.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/125627064/c1c2c6c5-d12d-419b-a578-0e41ff3061cc)
![IMG_20230909_220634_649.jpg](https://github.com/YT-Advanced/YT-Advanced/assets/125627064/0618fd4c-a511-4bf7-8971-ac32aefdd503)

**Comment by Kantotero** [comment]
> No dice on 2.190.2.
> 
> ![Screenshot_20230911_173417_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/144253206/97fb2a5c-dd2a-429f-981b-18c1531b419b)
> 

Works for me on latest YT ver. Maybe you didn't enable the hide flyout menu

**Comment by Kantotero** [comment]
> No dice on 2.190.2.
> 
> ![Screenshot_20230911_173417_ReVanced Extended](https://github.com/YT-Advanced/YT-Advanced/assets/144253206/97fb2a5c-dd2a-429f-981b-18c1531b419b)
> 

Works for me on latest YT ver. Maybe you didn't enable the hide quality flyout menu

**Comment by StradivariusKane** [comment]
I have it enabled yes, I even uninstalled and reinstalled.
