### ISSUE TITLE
Whitelist Channel Speed

### ISSUE THREAD

**Issue by Menlab86** [YT-Advanced/YT-Advanced#113]
Hi thanks so much for adding back the channel whitelist for speed its really helpful
but its not acting properly

1. if i whitelist a channel and go to whitelist a second one it says adding the first channel to whitelist and not the second one I.e. it only keeps the id for the first channel.

2. sometimes it still does x2 speed for the whitelisted channel

3. sometimes going from whitelisted channel to random channel it keeps the x1 speed instead of my default speed which is x2

i have attached screenshot of my settings and a video
as you can see in the video i add a channel to whitelist and then when i click on a video from a differnt channel it
1. went to x1 speed instead of x2
2. when i click whitelist on second channel it shows first channel name and as can see in screenshot did not add the second channel to whitelist

Please Fix
Thanks so much

https://github.com/YT-Advanced/YT-Advanced/assets/143924564/7d2b5779-5d60-4ef2-af9e-327be905371a

![Screenshot_20230903_020149_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/143924564/792972e9-129a-4942-b602-179d62de3439)
![Screenshot_20230903_020257_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/143924564/c953d282-6c82-4891-a781-72448436a01e)

**Comment by YT-Advanced** [comment]
Thanks for your report

**Comment by YT-Advanced** [comment]
@Menlab86 Hello, I'm back. Can you check SponsorBlock too ?

**Comment by Menlab86** [comment]
> @Menlab86 Hello, I'm back. Can you check SponsorBlock whitelist too ?

So it has the same issue of adding channels that it only gets the first channel name

But from the little testing i did it looks like its working correctly

**Comment by YT-Advanced** [comment]
@Menlab86 So did the problem solved ? Can you explain more

**Comment by Menlab86** [comment]
> @Menlab86 So did the problem solved ? Can you explain more

I was writing about sponsorblock was acting fine
But on latest update there is no option for sponsorblock

The speed issues are still the same as original post nothing was fixed

**Comment by YT-Advanced** [comment]
> But on latest update there is no option for sponsorblock

It is strange, did you included SponsorBlock patch ?
> I was writing about sponsorblock was acting fine

If SponsorBlock worked, Speed should worked too

**Comment by Menlab86** [comment]
> > But on latest update there is no option for sponsorblock
> 
> It is strange, did you included SponsorBlock patch ?
> 
Yes
> > I was writing about sponsorblock was acting fine
> 
> If SponsorBlock worked, Speed should worked too
But it doesnt

**Comment by YT-Advanced** [comment]
> But on latest update there is no option for sponsorblock

Can you take a screenshot about this problem

**Comment by Menlab86** [comment]
Here
![Screenshot_20230910_021141_YouTube](https://github.com/YT-Advanced/YT-Advanced/assets/143924564/f8696964-88de-4351-9c6b-7e12033d0b52)


As you can see from the seekbar sponsorblovk is enabled ad the green bar is there

**Comment by YT-Advanced** [comment]
@Menlab86 Thanks, I can confirm it. Also can you build latest patch with v18.19.xx for testing. Thanks

**Comment by Menlab86** [comment]
> @Menlab86 Thanks, I can confirm it. Also can you build latest patch with v18.19.xx for testing. Thanks

sorry for the late response i tried with version 18.19.36 and it still didnt work

**Comment by YT-Advanced** [comment]
> > @Menlab86 Thanks, I can confirm it. Also can you build latest patch with v18.19.xx for testing. Thanks
> 
> sorry for the late response i tried with version 18.19.36 and it still didnt work

Which ones you are mentioning ? SponsorBlock or the bug in your issues ?

**Comment by Menlab86** [comment]
> > > @Menlab86 Thanks, I can confirm it. Also can you build latest patch with v18.19.xx for testing. Thanks
> > 
> > 
> > sorry for the late response i tried with version 18.19.36 and it still didnt work
> 
> Which ones you are mentioning ? SponsorBlock Whitelist not shown or the bug in your issues ?

All the issues

**Comment by YT-Advanced** [comment]
@Menlab86 Sorry for disturbing you, but can u check back

**Comment by Menlab86** [comment]
> @Menlab86 Sorry for disturbing you, but can u check back

What shpuld i check?

**Comment by YT-Advanced** [comment]
Check Whitelist SponsorBlock to make sure that it have the same problem like Whitelist Channel Speed

**Comment by Menlab86** [comment]
so in summary
Whitelist Channel Speed

1. if i whitelist a channel and go to whitelist a second one it says adding the first channel to whitelist and not the second one I.e. it only keeps the id for the first channel.

2. it does x2 speed for the video of whitelisted channel and then switches to x1 for all other videos (including other channels) even tho default speed is set to x2 and save video speed is turned off

Whitelist SponsorBlock

1. if i whitelist a channel and go to whitelist a second one it says adding the first channel to whitelist and not the second one I.e. it only keeps the id for the first channel.

But issue 2 is not a issue for sponsorbloc

Hopefully this is clear enoght
(i should be able to test now right away instead of 2 days late :))

**Comment by YT-Advanced** [comment]
For the second issues, seem like I have do something wrong 💀
And the first issues, I will take a look soon

**Comment by YT-Advanced** [comment]
@Menlab86 I have fixed, can you recheck again ?

**Comment by Menlab86** [comment]
> @Menlab86 I have fixed, can you recheck again ?

So now its cathing the channels to add to whitelist
Sponsorblock works perfectly

But speed is still not working properly
So if i click on a video that is whitelisted and change speed to x1 and then click on another video whitelisted (even othen channel) it stays x1 speed but if speed is changed to x2 speed or i click on another video from non whitelisted channel so speed changes to x2 speed it will not go back to x1 speed on whitelisted video

So it looks like the whitelist is preventing speed from changing to the default speed but does not change the speed to x1

Thanks for the fixes hopefully this is a easy fix

**Comment by Menlab86** [comment]
Any chance this can be fixed?
Thanks so much

**Comment by nochlab1** [comment]
Hi can you open a pr request on youtube extended?
And if possible for it to be fixed if not then just the current configuration
Thank you

**Comment by YT-Advanced** [comment]
> Hi can you open a pr request on youtube extended?
> And if possible for it to be fixed if not then just the current configuration
> Thank you

You can open an feature request so inotia can readd Whitelist Speed and Whitelist SB

**Comment by nochlab1** [comment]
> > Hi can you open a pr request on youtube extended?
> > And if possible for it to be fixed if not then just the current configuration
> > Thank you
> 
> You can open an feature request so inotia can readd Whitelist Speed and Whitelist SB

there is no option for patch request for youtube
would he get upset if i put it under bug report?

**Comment by YT-Advanced** [comment]
@nochlab1 You can put it in Bug Report, since nobody request it so he didn't add it

**Comment by nochlab1** [comment]
It was closed saying not being added
