### ISSUE TITLE
YouTube crashes with both spoofing options enabled when patched with RVX Manager

### ISSUE THREAD

**Issue by Kuddus73** [YT-Advanced/YT-Advanced#13]
https://github.com/YT-Advanced/YT-Advanced/assets/127908708/1ac990bd-f313-4591-9aca-69462686753d

**Comment by YoghurtAndPizza** [comment]
Not able to reproduce on my side with both options enabled.

**Comment by Kuddus73** [comment]
> Can you share the log

I don't know how to do it and I don't have a pc.

If I patch it with Revancify, YouTube doesn't crash tho and everything works fine.

**Comment by YT-Advanced** [comment]
> > Can you share the log
> 
> I don't know how to do it and I don't have a pc.
> 
> If I patch it with Revancify, YouTube doesn't crash tho and everything works fine.

Your problem have been solved ?

**Comment by Kuddus73** [comment]
> Your problem have been solved ?

The problem isn't fixed:
- If I patch YouTube with RVX Manager, when I enable both spoofing options, YouTube crashes.
- If I patch YouTube with Revancify, even with both spoofing options enabled, YouTube works fine.

So, there's something wrong.

**Comment by YT-Advanced** [comment]
Maybe my patch is not fully compatiable with RVX Manager 🤔

**Comment by YoghurtAndPizza** [comment]
Now that I took a closer look for RVX Manager (inotia00), I noticed that it's adding in patches that I deselected, for example Language Switch. So there is some compatibility issues.

**Comment by YT-Advanced** [comment]
Seem like it is solved
